name: mitmproxy

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      now: ${{ steps.now.outputs.now }}
    steps:
      - id: now
        run: echo "now=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
  build-amd64:
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./mitmproxy/
          push: true
          provenance: false
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:amd64-${{ needs.prepare.outputs.now }}
  build-arm64:
    runs-on: ubuntu-latest
    needs:
      - prepare
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.9.0
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./mitmproxy/
          push: true
          provenance: false
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:arm64-${{ needs.prepare.outputs.now }}
  combine-images:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - prepare
      - build-amd64
      - build-arm64
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker Manifest GitHub Action(latest)
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:latest
          push: true
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:amd64-${{ needs.prepare.outputs.now }},${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:arm64-${{ needs.prepare.outputs.now }}
      -
        name: Docker Manifest GitHub Action(date)
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: ${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:${{ needs.prepare.outputs.now }}
          push: true
          images: ${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:amd64-${{ needs.prepare.outputs.now }},${{ secrets.DOCKERHUB_USERNAME }}/mitmproxy:arm64-${{ needs.prepare.outputs.now }}
